### ISSUE TITLE
Will Save

### ISSUE THREAD

**Issue by 3E2NTI** [EndlesNights/dnd4eBeta#1]
The Will Save is not calculated correctly. Only the Wisdom bonus is taken into account (and not the Intelligence bonus if it is higher) and any Bonuses are not taken into account either. It is not possible to add bonuses in the context menu.

**Comment by NuptupTDOW** [comment]
This was an issue with the previous version of the sheet, but the last update should have fixed the calculations. However, I just want to remind you that Will defense is calculated with Wisdom and Charisma, not Wisdom and Intelligence, so that may be part of the problem for you. Also, my context menu bonuses seem to be working fine. Make sure you update your system and report back. :D

**Comment by 3E2NTI** [comment]
The last update fixed the problem, thank you! (and sorry, I meant Wis and Cha).

**Comment by NuptupTDOW** [comment]
> The last update fixed the problem, thank you! (and sorry, I meant Wis and Cha).

No problem, glad I could help!
