### ISSUE TITLE
[Request] Add level to weapon/armour/equipment/consumable sheet

### ISSUE THREAD

**Issue by FoxLee** [EndlesNights/dnd4eBeta#169]
Since almost all items in 4e have a level associated with them, it would be  useful to have this property included on their sheet. This could be used to provide a default value for cost as well, at least for magic items (since you can calculate that reliably once you know the item's level and whether or not it's a consumable).

It would be super useful if it were available to use in effects, since many effects scale with item level. (I don't know how feasible this is—I've only used actor properties in effects, and that may be the only way to use them—but if possible it would open up a ton of automation possibilities).

**Comment by draconas1** [comment]
@EndlesNights I think having the level there should be not too difficult?  - I am in 2 minds - just adding it as a text box (like on powers) would be individually easy, but need to be replicated to every different item type, I sort of want it in one of the standard header boxes - next to Rarity and Source.

@FoxLee need to disambiguate here, using it in "effects" in the sheet sense of the word (e.g. ones that you would use to change an actors stats) would be between very difficult and impossible (because of the way that effects are transferred onto actors it is entirely possible they lose their parent item, and even if they don't it will probably be hard to get them to find the level).  On the other hand, once level is exposed somewhere in the item UI adding `@itemLevel` that you could use in the items power formula (so for attacks and damage etc....) would be 1 line of code.  

I am generally in favour of this after my work on consumables.  But probably should not be trusted making a layout change to the top bar.

**Comment by FoxLee** [comment]
I was definitely thinking of effects that transfer to actor. I was afraid that might be impossible, given what I read about "transfer to actor" from other sources.

However, having it available only for self-contained powers would still be handy, since consumables like potions/alchemical frequently reference their level in hit/healing/damage formulae. It's a shame that it won't help with effect on equippable items, but if it's a trivial code change for consumables then I'd say let's take what we _can_ get!

This does increase my desire to split Wondrous items between "equipment" and "consumable" FVTT-item types, depending on whether they are "equippable but slotless" (tattoos, boons, shards etc) or "trinket with usable power" (banners, soulfangs, etc). Is that how it's intended to work? I noticed "Wondrous Item" doesn't seem to be selectable for any type of item, which suggests maybe yes.

**Comment by draconas1** [comment]
#181 implements level field for items and let it be used in the items formula using @itemLevel  The example alchemy all have the field populated, but do not make use of the variable as they are just starters.  

Also kept the level in the names of the xample consumables, because I want it to be obvious which is which when they show up in token bar.

**Comment by EndlesNights** [comment]
Thanks [draconas1](https://github.com/draconas1)
