### ISSUE TITLE
Can not edit power 0.1.0

### ISSUE THREAD

**Issue by InfiniteLearner** [EndlesNights/dnd4eBeta#19]
Hello,

My DM just installed the latest version of your game system and I was trying to add power and run into the following issue.
I or my DM can not edit powers.
This issue only seems to concern players that have been created before the update, any npc or players created afterward do not have this problem.

![click_edit_button](https://user-images.githubusercontent.com/29714758/114271391-c1ba3d00-9a19-11eb-98be-921a653bbc60.PNG)
![edit_power_error](https://user-images.githubusercontent.com/29714758/114271395-c54dc400-9a19-11eb-8e68-563f727268dd.PNG)

Thanks for the amazing job.

Best regards.

**Comment by EndlesNights** [comment]
This is because I haven't gotten around to setting up any data migration services just yet. Currently going from the 0.0.x to the 0.1.x branch more or less means you'll need to make a new character and new power/items because of some internal changes I've been working on. This is also why I haven't merged the dev (0.1.x) branch to the master (0.0.x) branch.

**Comment by cyprienGuenard** [comment]
Ok thanks for the precision.
We'll wait for the merge to master.
Keep up the good job.
