### ISSUE TITLE
[REQUEST] - Limited view of character sheets

### ISSUE THREAD

**Issue by Kiljax** [EndlesNights/dnd4eBeta#213]
Would it be possible to have a limited view for character sheets. 

Right now, no matter what view is selected, all players gain access to all stats, at-will powers, etc.

For NPCs or other characters, it would be nice to have a simple 'image' at the top, biography details underneath and nothing else for the players to see. 

Thank you for your time

**Comment by NuptupTDOW** [comment]
I would heavily suggest basing it off of the Pathfinder 2e set-up where you can set permissions as limited, and when someone opens a sheet that they only have limited access to, it shows the character art and then a short biography (similar to the Roll20 first tab now that I think about it). You could definitely do something like that, or just make it so that the limited view shows only character art and the biography and details tabs.

**Comment by mncimino1993** [comment]
Would like to chime on this to say it would be really helpful. 

Currently I'm duplicating every NPC as a lvl 1 base npc just so the players can put a face to all the people I throw at them.

**Comment by mncimino1993** [comment]
I just submitted a pull request for this.-

**Comment by EndlesNights** [comment]
Fixed with merged #228
