### ISSUE TITLE
Effects for increasing attack and damage by damage type keyword not working

### ISSUE THREAD

**Issue by aleneshazam** [EndlesNights/dnd4eBeta#247]
As title suggests, effects that increase attack and damage mods via keywords aren't functioning. For example a Versatile Expertise style effect still functions as normal (weapon.attack.bladeH.feat for example), but a Fiery Blood style effect (power.attack.fire.untyped) doesn't add any bonuses.

**Comment by NuptupTDOW** [comment]
It's been a while since I messed with that style of custom effects, but try (power.attack.fire.value) instead. I know for some things, like ac and nads, the untyped tag doesn't always work, but the value tag does. I'm not sure if this is intended as I'm not a dev for this, but I believe the work-around above will work.

**Comment by draconas1** [comment]
We've seen this on the discord, I suspect it broke in 0.3.7 and will try to look at it if @EndlesNights doesn't get to it first.

**Comment by EndlesNights** [comment]
Found it, accidently changed a variable I wasn't suppose to change while adding in damage type overrides to weapons. Patch should be out shortly that fixes this.
