### ISSUE TITLE
Generate new hooks for macros and modules to use

### ISSUE THREAD

**Issue by YellowAdder** [EndlesNights/dnd4eBeta#255]
Feature Request:

The addition of new hooks to the 4E system benefits macro authors and module creators (and by extension the players aided by these additions). These could potentially allow features like handling buffs/debuffs that expire after a character's next attack or damage roll, or handling specialized bonuses to saving throws (e.g., a gnome's +5 vs. illusions or an eladrin's +5 vs. charm effects).

As an example reference, I would point to a module created for the 5E system that provides a library of new hooks meant for later inclusion to that system:

https://github.com/ElfFriend-DnD/foundryvtt-more-hooks-5e

There are six that I'd request initially, similar to some found in the above reference:

- preRollDamage
- rollDamage
- preRollAttack
- rollAttack
- preRollSave
- rollSave

(Possibly also preRollDeathSave and rollDeathSave hooks if it's not possible to detect that a particular save is made as a death save with the more generic hooks.)

**Comment by draconas1** [comment]
So I had a look at doing this today, hoping it would be an easy add, it is unfortunately quite non-trivial due to the way the roll code currently works.  

It's doable, but we are talking multiple hours of refactoring and testing that we haven't screwed it up.  I'm not saying it's not something we would do, but you will need to make a strong case for it and what it actually will enable. (Note that automation relying on this for a 5e game will not work for us because our hook events will be different and the configs we pass are substancailly different)

**Comment by YellowAdder** [comment]
Sounds like it might have a better start as an external module with potential for integration if it proves out well later. Thanks for taking the time to consider the request, @draconas1!
