### ISSUE TITLE
Are rituals broken, or is this unique to me?

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#259]
I can always manually roll rituals, but if I'm doing something wrong, I'd love to know what:

![image](https://user-images.githubusercontent.com/5306827/215923491-57bb670f-4a32-4de3-9440-af6e339ce833.png)

Also, thanks again to everyone for this amazing 4e system and the supporting modules. This continues to amaze.

**Comment by FoxLee** [comment]
I ran some tests on this, since I was afraid I'd broken it somehow with my chat output tweaks! Using the Cure Disease ritual straight from the compendium importer, I found this:

- Out of the box, it has no skill and no formula set, and rolling it throws an error.
- Entering the formula you have there makes it roll zero values, just like your example.
- Setting the skill _only_ makes it work correctly.

Could you try it with no formula and see if it works then?

Further info of dev relevance: As an experiment, I entered the text used as a placeholder for the roll formula (1d20 + @attribute). This appears to roll the d20 but returns 0 for @attribute, so there's probably an issue with that variable. Using other variables on the @attr.attr.attr path seems to work as expected, but testing with a "tool" (the other place where @attribute is supposed to work) I get an "unresolved StringTerm undefined" error, so that certainly seems to be an issue we need to look into.

**Comment by drywallmud** [comment]
By the way, your styling add-on is amazing!

**Comment by draconas1** [comment]
yeah the @skill is definitely wrong.

I've gone looking at the code, and there are some v10 bugs around managing the formula if you enter a custom formula, if you leave a blank formula it does down a different route and that still works.  (which is 1d20 + modifier of the selected skill)

**Comment by EndlesNights** [comment]
Use the `@attribute` tag for Rituals, Thanks to [draconas1](https://github.com/draconas1) for addressing the missed v9 to v10 issues.
