### ISSUE TITLE
V11 Compendium Changes

### ISSUE THREAD

**Issue by draconas1** [EndlesNights/dnd4eBeta#286]
I have started thinking about how to cut down and combine the number of compendiums in V11.

I've had a few ideas that I have listed here : https://docs.google.com/document/d/1gRATZrxANgJM-Tl-z-Q19gaRU3rQizG8IN-_sF2_hMo/edit?usp=sharing

I think I am leaning most towards option 3:  I like fewest number of compendiums possible, to have a very easy "where do I go for my stuff?" and idea 3 is: Class/Race, Powers, Equipment.  That should also make for faster loading as the game only has to transfer the metadata for 3 compendiums across.    Also having them default into a folder so its obvious "these are the system resources". 

@EndlesNights @FoxLee what are your thoughts?  (if you DM me an email on discord I can give you write access to the document if you want to edit / add more)

Also anyone else who happens to be watching feel free to chime in ;)

**Comment by EndlesNights** [comment]
There are two layers of folders for compendiums within v11. Intern and External folders. As part of the v11 conversion I just set up some simple external folders for all the compendiums of the system. So everything currently looks like this: 
![image](https://github.com/EndlesNights/dnd4eBeta/assets/58280840/88380d3f-adde-4346-9f41-6504a50cb579)
Which already makes the experiencer much more clean and manageable, and less over whelming to look at.

But I like your further explanation for going with idea 3.

**Comment by FoxLee** [comment]
My philosophy on it has been "big compendia, many folders"! I pretty much combined mine as much as Foundry would allow based on data type, and used only internal folders for organisation <XD So, options 2 and 3 are definitely more to my tastes.

Honestly I'd _probably_ chuck em all in together if it were just me, but I do think the top-level groups you suggest feel nice and logical, and like practical-sized chunks. Like I wouldn't have a problem with that. [Items/Features/Powers] (aka option 3) really feels like it's describing the three fundamental 4e "data types" (at least in terms of character creation) so that's the one I like best, too.

**Comment by EndlesNights** [comment]
What was done, Good job team!

**Comment by draconas1** [comment]
Sweet, thanks! :)
