### ISSUE TITLE
Critical hits are not functioning. 

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#3]
When clicking damage and selecting to roll a critical damage roll, I consistently get a red bar notification stating, "SyntaxError: Invalid or unexpected token" I can't seem to find a way around this. 

Edit: upon further inspection, it seems my error is likely caused by the brutal 2 calculation I mentioned in my other issue I posted "d6r<3" since it doesn't know how to maximize that. This is an edge case and likely shouldn't be a priority. I have tested it without this kind of text and it maximizes fine.

**Comment by EndlesNights** [comment]
I only ever intended for numbers to be used in the "Damage Dice Size", and the way critical are handled by default in the dice script is as "@wepDiceNum*@wepDiceDamage" which in this case is being resolved to "1*6r<3"  which is an invalid roll. So currently I'm unsure whether I'd prefer to allow the Roll Modifies to continue to be used in association with weapon stats. One one had it provides more options for interesting weapons designs, but it also requires setting up a function to check all damage rolls to ensure they are valid before rolling, and to find an appropriate fix so that the value will pas.

I think for the intern I'm going to switch the Damage Dice Num and Damage Dice Size to only take numerical values in their fields, and I may revisit this later.

**Comment by NuptupTDOW** [comment]
This will currently break my working fix for brutal, but assuming you get it to work with your idea, that's not too bad. However, I will say that, I don't really think you need to worry yourself with people breaking the sheet with improper inputs. I mean, me having it act buggy is the exact reason I was able to find a different work around that send to work. But if you remove the ability to add anything other than numbers, it prevents adding plus signs.

**Comment by NuptupTDOW** [comment]
Your fix on the brutal weapon trait retroactively fixed this. Thanks!
