### ISSUE TITLE
Attacks are getting +1d20

### ISSUE THREAD

**Issue by mageofthesands** [EndlesNights/dnd4eBeta#30]
Foundry 0.8.7
4th Edition Beta 0.2.3

No changes to the powers or equipment.  No new modules, no modules installed that do anything with rolls, except for "Dice Tray."

Attacks now seem to be 1d20kh + 1d20 + etc.  
![1d20kh 6 16 21](https://user-images.githubusercontent.com/81931767/122295565-f8e81700-cebe-11eb-8d61-341e8e7c5202.jpg)

**Comment by EndlesNights** [comment]
There has been a slight reworking to how d20 rolls are handled in in regards to attack roll formulas. They're no longer in the main formula but as it's own separate part that's determined in the roll dialog. This was to account for both attack and skill checks that conditionally require mullite dice rolls where one d20 is dropped (normally the lower one) instead of requiring the user to roll multiple times over.
This does create a strange kerfuffle for already existing powers, and requires that a tab bit of editing on the users part to fix and will explain where the extra d20 is coming from. But I think it will be a better solution moving forward.

I could probably have documented the change a little better, and get better text that explains the new part of the rolling interface that has to do with d20s. The number represents the base number of d20s that will be rolled. A positive number means keeping the highest die value rolled, while a negative means keeping the lowest die rolled. A zero would mean no d20 rolls.
![image](https://user-images.githubusercontent.com/58280840/122324025-1684a300-cef6-11eb-8f02-438a08539d61.png)

**Comment by mageofthesands** [comment]
In other words, the 1d20 in the Attack Formula needs to be removed?  

Ah, this is for Avengers, basically.  And the other "5E Advantage" stuff.

**Comment by EndlesNights** [comment]
Basically, but without calling it Advantage/disadvantage. A surprising amount of 4e powers / feats give you "advantage" style conditions. Then there is the avenger who has it as part of their kit for their designation.
