### ISSUE TITLE
Built in Second Wind Button Bonuses Incorrectly Expire at End of Turn, not Start of Next Turn

### ISSUE THREAD

**Issue by drywallmud** [EndlesNights/dnd4eBeta#389]
As title says, you don't get to enjoy the automated defences as they disappear at the end of turn. Been an issue for a while, not sure if this is known.

**Comment by FoxLee** [comment]
This seems to be a problem with the "Start of User's Next Turn" duration in all cases. (Confirmation appreciated if you can.) I imagine something is handled incorrectly in the turns logic.

**Comment by drywallmud** [comment]
Oddly, "Start of User's Next Turn" duration on custom powers seem to work incorrect as well, but it expires one character later on the combat tracker for me. It's always the built in button's effect that seems to end at end of turn, despite being labelled the same "Start of User's Next Turn" as the other effects. Maybe this will give some insight on the expiry behavior.

**Comment by FoxLee** [comment]
Just had a breakthrough on this; firstly, I've discovered that by default, no tiebreaker is being applied to initiative, meaning that you can have "perfect" ties. Since effect duration is interpreted based on the current turn's initiative, any effect on an actor who shares an initiative with the actor before them is getting screwed up.

That covers the weirdness I was observing, but not the Second Wind issue. That appears to be down to the second wind activation not causing applyEffectsToTokens() to fire (unlike manual SoUNT effects) which I think is preventing it from calculating proper expiry timing.

**Comment by FoxLee** [comment]
Bleh, I'm struggling to find angle of approach for the applyEffectsToTokens() problem; I'm very unfamiliar with that part of the system, and it's hard to learn by looking because of the more complex structure. I hate to say it, but for this particular problem I might have to tag out. (I'll upload what I've done to fix the initiative issue, of course!)

@EndlesNights, can you think of a smart way to fix this one? I'm pretty sure I've narrowed down the problem, just not sure where to go from here >3>;

**Comment by EndlesNights** [comment]
Sorry this took me a while to finally get around to this, but I have written the fix for this and it should be fixed in patch 0.5.10
