### ISSUE TITLE
Can't open character sheets after updating foundry?

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#43]
So, as the title says, new world, updated base foundry, updated 4e beta, can't open newly created character sheets.

**Comment by ahoward-cf** [comment]
Hi, I dont appear to have any issue opening either existing or new character sheets after updating Foundry. 

What version of Foundry and what version of 4e beta are you using? 

It should be noted, that the master branch of 4e beta is outdated, as both Foundry itself, and the system, have been going through rapid changes. I would advise trying the dev branch of 4e beta if you are having difficulties (which also comes with some major improvements). I can help you set that up if you need to.

**Comment by NuptupTDOW** [comment]
I would greatly appreciate that. I have done a fresh world with the game system installed and fully updated foundry and it won't let me open a character sheet. 0.8.9 Foundry, 0.1.4 4th Edition Beta. Not sure why I'm having these problems...

**Comment by EndlesNights** [comment]
The 4e 0.1.4 Version was only for Foundry 7.10, when Foundry switched over to 8.x they made smore major changes to how some data structures works which is why your compatibility broke. And so the Beta 0.2.X is the version that's compatable with Foundry 8.X

I've  just rebranched the dev branch to the main branch so that it's now in line with where I am and Foundry is currently in development. If you would like to use your older version you will need to go back to Foundry 7.X, if you would like to use the latest stable version of Foundry, you should be able to do so with the current newest Beta version of 0.2.24.
