### ISSUE TITLE
Formula for "Brutal" damage on weapons is buggy.

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#5]
Entering a value such as "6r<3" for the "Damage Dice Size" of a weapon to reroll 1's and 2's (for a brutal 2 weapon i.e. a Large sized Execution Axe) will sometimes still accept a 1 or a 2 as an acceptable number and not reroll it. It rerolls most of them, but keeps some of them and I can't discern any pattern for when it will do it. I also tried "d6r1,2" and it functions the same, sometimes working, but eventually failing.

**Comment by EndlesNights** [comment]
This is something that is part of Foundry, the way the reroll dice function is setup is that it will only ever do one single reroll, and it will not check the value of any new dice values against the reroll threshold. This is more noticeable if you were to input multiple single dice rolls command of "/r 1d6r<3" over and over again and you will notice you will still get the occasion results of 1 or 2.

There is no current way to get around this as I don't believe I can implement new dice terms or modify how exiting ones currently work, so I will have to add a check for the "Brutal" property on a given weapon within the damage roll function and correct the numbers from their.

**Comment by NuptupTDOW** [comment]
Do you think a temporary fix could just be done by making the weapon "damage dice size" field read as "d4+2" instead of "d6r<3" since, it's functionally the same? Or, would the "+2" cause issues down the road with crit functions?

**Comment by EndlesNights** [comment]
That proposal works well for powers that deal 1[w] damage, but starts to run into issues when you start to use powers that deal >=2[w] since you would start to miss out on each additional +4 damage per additional 1[w].
Anyway I have a solution that seems to be working, when the powers damage formula is being converted into numbers for the Rolling function, it checks for the brutal weapon property, and if it's brutal, it subtracts 2 from the dice size, and then adds the adds a bonus of +2 * ("Damage Dice Num" + n[w]). Bit of a hacky approach using regex, and it will only find the n[w] if it's to the left @wepDiceNum.

I'll see if a dice modifier can be added in that supports unlimited rerolls if the number is below a target threshold.

**Comment by NuptupTDOW** [comment]
"starts to run into issues when you start to use powers that deal >=2[w]" 

Maybe I'm mis-remembering my experience when working on this option, but I certainly think that my text character (a berserker) was having no such multiplicative error when using 3[w] attacks such as avalanche strike out blood hunt rage. I can more directly demonstrate it to you in discord if you'd like. 


"and if it's brutal, it subtracts 2 from the dice size, and then adds the adds a bonus of +2"

Just remember that there are brutal 1 weapons as well.


"dice modifier can be added in that supports unlimited rerolls"

With either of our suggested fixes, would this even be necessary?

**Comment by NuptupTDOW** [comment]
Thanks for the fix!
