### ISSUE TITLE
Weapliments not functional

### ISSUE THREAD

**Issue by NuptupTDOW** [EndlesNights/dnd4eBeta#6]
If you create a weapon such as a greatsword in the inventory and give it the trait "Implement" it becomes a valid implement choice for your powers, however it still calculates the weapon's proficiency bonus for implement attacks because the power calls upon "@wepAttack". I am temporarily fixing this by just placing a "-3" before that callout to offset the proficiency bonus, but it would be great if, when you select "implement" under the "Weapon Required" selection, it could change the attack formula to call on a new value such as "@impAttack" which will completely ignore the proficiency of the associated item if one exists, such as for weapliments.

**Comment by NuptupTDOW** [comment]
Alternatively, you could just separate the weapon attack bonus attribute into 2 separate attributes (prof) and (enhance) then players could manually remove prof from the formula text in the power card.

**Comment by EndlesNights** [comment]
Alright, so when a weapon is given the implement property, it will will now gain access to three new fields input fields in conjunction to its other existing ones.

Implement Proficiency Bonus (Though I suppose this is more for Implement Expertise feat.)
Implement Attack Formula, works similar to the default Bonus to Attack Formula. Referred to as "@impAttack"
Implement Damage Formula, works similar to the default Bonus to Damage Formula.  Referred to as "@impDamage"

Now when you create a Power, in the Attack or Damage formulas fields, instead referring to @wepAttack or @wepDamage, you can instead or also use @impAttack or @impDamage to get the weapons bonus as an implement. If you have not "Implement Proficient" Check Box marked on the weapon, both @impAttack and @impDamage will resolve as 0 instead of what ever values they have assigned to them. You can ignore proficiency requirements with an override notation of "@impAttackO" or "@impDamage0"

Similarly now in the weapon formulas "@profBonus" now requires the "Weapon Proficient" Check Box to be marked in order for it to resolve as its value. This requirement can again be ignored if you used the alternative override notation "@profBonusO".

**Comment by NuptupTDOW** [comment]
So, I could have sworn I replied to this, and maybe due to the way I jerry-rigged the weapons to work as a work-around, it may have broken it. But, currently I can't get that system above to work. It doesn't matter if I try implement arcane, implement divine, or unlabeled implement, it won't generate those new fields.

**Comment by EndlesNights** [comment]
I haven't pushed those to the manifest yet that's why.

**Comment by NuptupTDOW** [comment]
See, that'd explain it lol! No worries, I was just confused :p

**Comment by EndlesNights** [comment]
0.0.9 is now pushed.
